
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Jan 07 17:54:55 CET 2022
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PLUSPLUS = 40;
  public static final int LTE = 36;
  public static final int LBRACKET = 50;
  public static final int CONST = 7;
  public static final int CHAR = 24;
  public static final int LPAREN = 46;
  public static final int SEMI = 42;
  public static final int CONTINUE = 17;
  public static final int MINUS = 27;
  public static final int RPAREN = 47;
  public static final int AND = 37;
  public static final int LT = 35;
  public static final int RECORD = 21;
  public static final int OR = 38;
  public static final int COMMA = 44;
  public static final int BOOL = 25;
  public static final int CLASS = 4;
  public static final int DIV = 29;
  public static final int PLUS = 26;
  public static final int IF = 8;
  public static final int THIS = 18;
  public static final int DOT = 45;
  public static final int EOF = 0;
  public static final int MINUSMINUS = 41;
  public static final int RETURN = 14;
  public static final int RBRACKET = 51;
  public static final int EQUAL = 39;
  public static final int SUPER = 19;
  public static final int NEW = 11;
  public static final int error = 1;
  public static final int MUL = 28;
  public static final int PERCENT = 30;
  public static final int NUMBER = 23;
  public static final int NEQ = 32;
  public static final int BREAK = 3;
  public static final int IDENT = 22;
  public static final int VOID = 15;
  public static final int EQ = 31;
  public static final int GTE = 34;
  public static final int COLON = 43;
  public static final int LBRACE = 48;
  public static final int ELSE = 6;
  public static final int ENUM = 5;
  public static final int READ = 13;
  public static final int GOTO = 20;
  public static final int WHILE = 10;
  public static final int RBRACE = 49;
  public static final int EXTENDS = 16;
  public static final int PROG = 2;
  public static final int GT = 33;
  public static final int PRINT = 12;
  public static final int DO = 9;
}

